AnnaLogs/AnnaLogs/Models/ALogsViewModel.cs
using AnnaLogs.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Anna;
using System.Data;
using System.ComponentModel.DataAnnotations;

namespace AnnaLogs.Models
{
    public class ALogsViewModel
    {
        public DataRowCollection Logs { get; set; }
        public string? Last { get; set; }
        public string? Yesterday { get; set; }
        public string? Tommorow { get; set; }
        public DataRowCollection UniqeDates { get; set; }
        public List<string>? AllCont { get; set; }
        public string? channelName { get; set; }
    }
}

AnnaLogs/AnnaLogs/Models/ErrorViewModel.cs
using System;

namespace AnnaLogs.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AnnaLogs/AnnaLogs/Models/LogsViewModel.cs
using AnnaLogs.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Anna;
using System.Data;

namespace AnnaLogs.Models
{
    public class LogsViewModel
    {
        public List<string>? Logs { get; set; }
        public List<string>? Users { get; set; }
        public List<string>? AllCont { get; set; }
        public DataRowCollection Message { get; set; }
    }
}

AnnaLogs/AnnaLogs/Controllers/ALogsController.cs
using AnnaLogs.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Anna;
using System.Data;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System;

namespace AnnaLogs.Controllers
{
    public class ALogsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult ChannelLogs(string asd)
        {
            _ = asd;
            string testing = asd;
            DataRowCollection AllChannels = Db.ExecSqlCollection("Select Channel from Log", new object[] { });
            foreach(DataRow row in AllChannels)
            {
                if (testing == row.ItemArray[0].ToString())
                {
                    return ViewLog(testing, "");
                }
            }
            DataRow a = Db.ExecSql("Select Top 1 Channel from Log", new object[] { });
            testing = a.ItemArray[0].ToString();
            return ViewLog(testing,"");
        }

        public IActionResult ViewLog(string channLog,string datLog)
        {
            string DateTimeLog = datLog;
            return All(channLog, DateTimeLog);
        }
        public IActionResult All(string channLog, string date)
        {
            string YesterdayHelp = "";
            string TommorowHelp = "";
            string tempVar = channLog;
            DataRow x = Db.ExecSql("Select top 1 convert(varchar(10), Date, 120) from Log where (Channel = @p0) Order By Date DESC;", new object[] { tempVar });
            string nn = @x.ItemArray[0].ToString();
            string[] n = nn.Split(' ');
            if (date == "")
            {
                date = n[0];
            }
            DataRow YesterdayDate = Db.ExecSql("Select top 1 convert(varchar(10), Date, 120) from Log where ((Channel = '#Annabot')) and (Left(convert(varchar(10), Date, 120), 10)<@p1)  Order By Date DESC", new object[] { tempVar, date });
            DataRowCollection Values = Db.ExecSqlCollection("Select Id,UserNick,Message,Date,Channel from Log where (Channel = @p0) and (Left(convert(varchar(10), Date, 120), 10) =@p1);", new object[] { tempVar, date });
            DataRowCollection Dates = Db.ExecSqlCollection("Select Distinct convert(varchar(10), Date, 120) from Log;", new object[] { });
            if (YesterdayDate is null)
            {
                YesterdayHelp = date;
            }
            else
            {
                YesterdayHelp = YesterdayDate.ItemArray[0].ToString();
            }
            DataRow TommorowDate = Db.ExecSql("Select top 1 convert(varchar(10), Date, 120) from Log where ((Channel = '#Annabot')) and (Left(convert(varchar(10), Date, 120), 10)>@p1)  Order By Date ASC", new object[] { tempVar, date });
            if (TommorowDate is null)
            {
                TommorowHelp = date;
            }
            else
            {
                TommorowHelp = TommorowDate.ItemArray[0].ToString();
            }
            ALogsViewModel m = new ALogsViewModel()
            {
                Logs = Values,
                UniqeDates = Dates,
                channelName = tempVar,
                Last = date,
                Yesterday = YesterdayHelp,
                Tommorow = TommorowHelp
                };
            return View("All", m);
        }
    }
}

AnnaLogs/AnnaLogs/Controllers/HomeController.cs
using AnnaLogs.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AnnaLogs.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        
    }
}

AnnaLogs/AnnaLogs/Controllers/LogsController.cs
using AnnaLogs.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Anna;
using System.Data;

namespace AnnaLogs.Controllers
{
    public class LogsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult All()
        {

            LogsViewModel m = new LogsViewModel()
            {
            };
            return View(m); 
        }
    }
}

AnnaLogs/AnnaLogs/Views/ALogs/All.cshtml
@{
    @using AnnaLogs.Models
    @using Anna;
    @model ALogsViewModel

    @using System.Data
    @using System.Text
    string channLog = String.Empty;
    string datLog = String.Empty;
    var config = ConfigModel.DeserializeData("config.json");
    string DateForLink = @Model.Last;
}
<button class="ButtonScroll"onclick="Scrolling()">Do najnowszych</button>
<h2 class="test">@Model.channelName</h2>
<div  class="test">
    @{
        if (@Model.Yesterday != @Model.Last)
        {
            <form asp-controller="ALogs" asp-action="ViewLog" id="YEST">
                <input type="hidden" value="@Model.channelName" asp-for="@channLog"/>
                <input type="hidden" value="@Model.Yesterday" asp-for="@datLog"/>
                <input class="SwitchDays" type="submit" value=@Model.Yesterday />
            </form>
        }
        
<h2 style="margin-bottom:0;">@Model.Last</h2>
        if (@Model.Tommorow != @Model.Last)
        {
            <form asp-controller="ALogs" asp-action="ViewLog" id="TOM">
                <input type="hidden" value="@Model.channelName" asp-for="@channLog"/>
                <input type="hidden" value="@Model.Tommorow" asp-for="@datLog"/>
                <input class="SwitchDays"type="submit" value=@Model.Tommorow />
            </form>
        }
    }
</div>
<form class="test" asp-controller="ALogs" asp-action="ViewLog">
    <input type="hidden" value="@Model.channelName" asp-for="@channLog"/>
    <input list="dates" value=""asp-for="@datLog">
    <datalist id="dates">
        @foreach (DataRow row in Model.UniqeDates)
        {
            <option value=@row.ItemArray[0]></option>
        }
    </datalist>
    <input type="submit" value="Wyświetl" />
</form>
<div>
    @foreach (DataRow row in Model.Logs)
    {
        if (@row.ItemArray[1].ToString() == @config.nick.ToString())
        {
            <div class="logs">
                <p onclick="Show(this.id)" id="@row.ItemArray[0]" class="Anna white2115"><strong>@row.ItemArray[1]</strong> : @row.ItemArray[2]</p>
                @{
                    StringBuilder sb = new StringBuilder();
                    sb.Append("0");
                    string str1 = @row.ItemArray[0].ToString();
                    sb.Append(str1);
                    string zzz = sb.ToString();
                    string nn = @row.ItemArray[3].ToString();
                    string[] n = nn.Split(' ');
                }
                <span id="@zzz" class="JD">@n[1]</span>
            </div>
        }
        else
        {
            <div class="logs">
                <p onclick="Show(this.id)" id="@row.ItemArray[0]" class="white2115"><strong>@row.ItemArray[1]</strong> : @row.ItemArray[2]</p>
                @{
                    StringBuilder sb = new StringBuilder();
                    sb.Append("0");
                    string str1 = @row.ItemArray[0].ToString();
                    sb.Append(str1);
                    string zzz = sb.ToString();
                    string nn = @row.ItemArray[3].ToString();
                    string[] n = nn.Split(' ');
                }
                <span id="@zzz" class="JD">@n[1]</span>
            </div>
        }
    }
</div>
<button class="ButtonScroll"onclick="ScrollingUp()">Do najstarszych</button>
<script>
    let channelName = "@Model.channelName"
    channelName = channelName.replace("#",'')
     let ChannLink = "https://localhost:44301/ALogs/ViewLog/All?channLog=%23"+channelName
     let DateLink = "&datLog="+"@Model.Last"
     let link = ChannLink+DateLink
     document.addEventListener('keyup', (event) => {
    var name = event.key;
    if (name === 'ArrowLeft') {
      let form = document.getElementById("YEST");
            form.submit();
    }
    if (name === 'ArrowRight') {
      let form = document.getElementById("TOM");
            form.submit();
    }
    }, false);
    function Scrolling(){
        window.scrollTo(0, document.body.scrollHeight);
    }
    function ScrollingUp(){
        window.scrollTo(0, 0);
    }
    function Show(clickedId) {
        let search = '0'+clickedId
        let x = link+'#'+clickedId
        let s = document.getElementById(search)
        if(s.classList.contains('JDclicked')){
            s.classList.remove('JDclicked')
        }
        else{
            s.classList.add('JDclicked')
        }
        window.location.href = x
    }
</script>

AnnaLogs/AnnaLogs/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    @using System.Data
    @using Anna;
    string asd = String.Empty;
}

<div class="text-center">
    <h1 style="margin-top:2%" class="display-4" id="TitleIndex">Wybór kanału</h1>
    @{
        DataRowCollection Channels = Db.ExecSqlCollection("Select Distinct Channel from Log;", new object[] { });
    }
    <form asp-controller="ALogs" asp-action="ChannelLogs">
        <input list="channels" asp-for="@asd">
        <datalist id="channels">
            @foreach (DataRow dataRow in Channels)
            {
                <option value="@dataRow.ItemArray[0]"></option>
            }
        </datalist>
        <br /><br />
        <input type="submit" value="Zatwierdz" />
    </form>

</div>

AnnaLogs/AnnaLogs/Views/Logs/All.cshtml
@{
@using AnnaLogs.Models
@using Anna;
@model LogsViewModel
@using System.Data
@using System.Text
    DataRowCollection Dates=  Db.ExecSqlCollection("Select Date from Log;",new object[] {});
    foreach (DataRow zyd in Dates)
    {
        
    }
}
<h1 class="test">Tutaj nazwa kanalu</h1>
<form class="test">
<input type="date">
<input type="submit" value="Wyświetl"/>
</form>
<div>
    @{
        DataRowCollection Essa=  Db.ExecSqlCollection("Select Id,UserNick,Message,Date Channel from Log;",new object[] {});
    }
        @foreach (DataRow zyd in Essa){
            if (@zyd.ItemArray[1].ToString() == "BotenAnna2" || @zyd.ItemArray[1].ToString() == "BotenAnnaMichal"){
                <div class="logs">
                    <p onclick="Show(this.id)" id="@zyd.ItemArray[0]" class="Anna white2115"><strong>@zyd.ItemArray[1]</strong> : @zyd.ItemArray[2]</p>
                    @{
                        StringBuilder sb = new StringBuilder();
                        sb.Append("0");
                        string str1 = @zyd.ItemArray[0].ToString();
                        sb.Append(str1);
                        string zzz = sb.ToString();
                        string nn = @zyd.ItemArray[3].ToString();
                        string[] n = nn.Split(' ');
                    }
                    <span id="@zzz"class="JD">@n[1]</span>
                </div>
            }
            else{
                <div class="logs">
                    <p onclick="Show(this.id)" id="@zyd.ItemArray[0]" class="white2115"><strong>@zyd.ItemArray[1]</strong> : @zyd.ItemArray[2]</p>
                    @{
                        StringBuilder sb = new StringBuilder();
                        sb.Append("0");
                        string str1 = @zyd.ItemArray[0].ToString();
                        sb.Append(str1);
                        string zzz = sb.ToString();
                        string nn = @zyd.ItemArray[3].ToString();
                        string[] n = nn.Split(' ');
                    }
                    <span id="@zzz"class="JD">@n[1]</span>
                </div>
            }
        }
</div>
<script>
    function Show(clickedId) {
        let search = '0'+clickedId
        let x = 'All#'+clickedId
        console.log(search)
        let s = document.getElementById(search)
        if(s.classList.contains('JDclicked')){
            s.classList.remove('JDclicked')
        }
        else{
            s.classList.add('JDclicked')
        }
        window.location.href=x
    }
</script>

AnnaLogs/AnnaLogs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AnnaLogs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header  id="NoView">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container" style="margin-left:0;">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Wybór kanału</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        const Ind = document.getElementById("TitleIndex")
    if(Ind.innerText == "Wybór kanału"){
        document.getElementById("NoView").style.display="none";
    }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>